links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1791715
      results:
        - test: exception_details.py
          subtest: test_exception_details[new WeakSet()-expected25-False]
        - test: exception_details.py
          subtest: test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-False]
        - test: exception_details.py
          subtest: test_exception_details[Promise.resolve()-expected27-False]
        - test: exception_details.py
          subtest: test_exception_details[new Int32Array()-expected28-False]
        - test: exception_details.py
          subtest: test_exception_details[new ArrayBuffer()-expected29-False]
        - test: exception_details.py
          subtest: test_exception_details[window-expected31-False]
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1770731
      results:
        - test: exception_details.py
          subtest: test_exception_details[document.createElement('div')-expected30-True]
        - test: exception_details.py
          subtest: test_exception_details[document.createElement('div')-expected30-False]
        - test: result.py
          subtest: test_remote_values[document.createElement('div')-expected16-True]
        - test: result.py
          subtest: test_remote_values[document.createElement('div')-expected16-False]
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1793589
      results:
        - test: sandbox.py
          subtest: test_sandbox_with_empty_name
