links:
- product: firefox
  results:
  - subtest: test_await_promise_delayed[False]
    test: await_promise.py
  - subtest: test_await_promise_async_arrow[False]
    test: await_promise.py
  - subtest: test_invalid_function
    test: exception_details.py
  - subtest: test_exception_details[(Symbol('foo'))-expected13-True]
    test: exception_details.py
  - subtest: test_exception_details[(Symbol('foo'))-expected13-False]
    test: exception_details.py
  - subtest: test_exception_details[(()=>{})-expected16-True]
    test: exception_details.py
  - subtest: test_exception_details[(()=>{})-expected16-False]
    test: exception_details.py
  - subtest: test_exception_details[(function(){})-expected17-True]
    test: exception_details.py
  - subtest: test_exception_details[(function(){})-expected17-False]
    test: exception_details.py
  - subtest: test_exception_details[(async ()=>{})-expected18-True]
    test: exception_details.py
  - subtest: test_exception_details[(async ()=>{})-expected18-False]
    test: exception_details.py
  - subtest: test_exception_details[(async function(){})-expected19-True]
    test: exception_details.py
  - subtest: test_exception_details[(async function(){})-expected19-False]
    test: exception_details.py
  - subtest: test_exception_details[new WeakMap()-expected24-True]
    test: exception_details.py
  - subtest: test_exception_details[new WeakMap()-expected24-False]
    test: exception_details.py
  - subtest: test_exception_details[new WeakSet()-expected25-True]
    test: exception_details.py
  - subtest: test_exception_details[new WeakSet()-expected25-False]
    test: exception_details.py
  - subtest: test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-True]
    test: exception_details.py
  - subtest: test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-False]
    test: exception_details.py
  - subtest: test_exception_details[Promise.resolve()-expected27-True]
    test: exception_details.py
  - subtest: test_exception_details[Promise.resolve()-expected27-False]
    test: exception_details.py
  - subtest: test_exception_details[new Int32Array()-expected28-True]
    test: exception_details.py
  - subtest: test_exception_details[new Int32Array()-expected28-False]
    test: exception_details.py
  - subtest: test_exception_details[new ArrayBuffer()-expected29-True]
    test: exception_details.py
  - subtest: test_exception_details[new ArrayBuffer()-expected29-False]
    test: exception_details.py
  - subtest: test_exception_details[document.createElement('div')-expected30-True]
    test: exception_details.py
  - subtest: test_exception_details[document.createElement('div')-expected30-False]
    test: exception_details.py
  - subtest: test_exception_details[window-expected31-True]
    test: exception_details.py
  - subtest: test_exception_details[window-expected31-False]
    test: exception_details.py
  - subtest: test_params_realm_unknown
    test: invalid.py
  - subtest: test_remote_values[(Symbol('foo'))-expected0-True]
    test: result.py
  - subtest: test_remote_values[(Symbol('foo'))-expected0-False]
    test: result.py
  - subtest: test_remote_values[(()=>{})-expected3-True]
    test: result.py
  - subtest: test_remote_values[(()=>{})-expected3-False]
    test: result.py
  - subtest: test_remote_values[(function(){})-expected4-True]
    test: result.py
  - subtest: test_remote_values[(function(){})-expected4-False]
    test: result.py
  - subtest: test_remote_values[(async ()=>{})-expected5-True]
    test: result.py
  - subtest: test_remote_values[(async ()=>{})-expected5-False]
    test: result.py
  - subtest: test_remote_values[(async function(){})-expected6-True]
    test: result.py
  - subtest: test_remote_values[(async function(){})-expected6-False]
    test: result.py
  - subtest: test_remote_values[new WeakMap()-expected11-True]
    test: result.py
  - subtest: test_remote_values[new WeakMap()-expected11-False]
    test: result.py
  - subtest: test_remote_values[new WeakSet()-expected12-True]
    test: result.py
  - subtest: test_remote_values[new WeakSet()-expected12-False]
    test: result.py
  - subtest: test_remote_values[new Error('SOME_ERROR_TEXT')-expected13-True]
    test: result.py
  - subtest: test_remote_values[new Error('SOME_ERROR_TEXT')-expected13-False]
    test: result.py
  - subtest: test_remote_values[new Int32Array()-expected14-True]
    test: result.py
  - subtest: test_remote_values[new Int32Array()-expected14-False]
    test: result.py
  - subtest: test_remote_values[new ArrayBuffer()-expected15-True]
    test: result.py
  - subtest: test_remote_values[new ArrayBuffer()-expected15-False]
    test: result.py
  - subtest: test_remote_values[document.createElement('div')-expected16-True]
    test: result.py
  - subtest: test_remote_values[document.createElement('div')-expected16-False]
    test: result.py
  - subtest: test_remote_values[window-expected17-True]
    test: result.py
  - subtest: test_remote_values[window-expected17-False]
    test: result.py
  - subtest: test_remote_value_promise_no_await
    test: result.py
  - subtest: test_invalid_script[root-True]
    test: result_ownership.py
  - subtest: test_invalid_script[none-False]
    test: result_ownership.py
  - subtest: test_invalid_script[None-False]
    test: result_ownership.py
  - subtest: test_return_value[root-True-False]
    test: result_ownership.py
  - subtest: test_return_value[none-False-False]
    test: result_ownership.py
  - subtest: test_return_value[None-False-False]
    test: result_ownership.py
  - subtest: test_strict_mode
    test: strict_mode.py
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1790021
