links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1791715
      results:
        - test: exception_details.py
          subtest: test_exception_details[new WeakSet()-expected25-False]
        - test: exception_details.py
          subtest: test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-False]
        - test: exception_details.py
          subtest: test_exception_details[Promise.resolve()-expected27-False]
        - test: exception_details.py
          subtest: test_exception_details[new Int32Array()-expected28-False]
        - test: exception_details.py
          subtest: test_exception_details[new ArrayBuffer()-expected29-False]
        - test: exception_details.py
          subtest: test_exception_details[document.createElement('div')-expected30-False]
        - test: exception_details.py
          subtest: test_exception_details[window-expected31-False]
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1841786
      results:
        - test: exception_details_await_promise.py
          subtest: test_exception_details[[1, 2][Symbol.iterator]()-expected28]
        - test: exception_details_await_promise.py
          subtest: test_exception_details['mystring'[Symbol.iterator]()-expected29]
        - test: exception_details_await_promise.py
          subtest: test_exception_details[(new Set([1,2]))[Symbol.iterator]()-expected30]
        - test: exception_details_await_promise.py
          subtest: test_exception_details[(new Map([[1,2]]))[Symbol.iterator]()-expected31]
        - test: exception_details_await_promise.py
          subtest: test_exception_details[new Proxy({}, {})-expected32]
        - test: exception_details_await_promise.py
          subtest: test_exception_details[(function*() { yield 'a'; })()-expected33]
